"""initial schema

Revision ID: 952724218c0f
Revises: 
Create Date: 2026-07-13 19:48:33.588199
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '952724218c0f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=False),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('changed_by', sa.Enum('patient', 'operator', name='loggedby'), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('basal_log',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('time_taken', sa.Time(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('correction_event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('bg_before', sa.Integer(), nullable=False),
    sa.Column('bg_after', sa.Integer(), nullable=False),
    sa.Column('bg_after_time', sa.DateTime(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('iob_at_start', sa.Float(), nullable=False),
    sa.Column('food_in_window', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('dish',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('portion_unit', sa.String(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('IFCT2017', 'USDA', 'label', 'estimated', name='dishsource'), nullable=False),
    sa.Column('is_favourite', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('dish_id')
    )
    op.create_table('meal_event',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('logged_by', sa.Enum('patient', 'operator', name='loggedby'), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='mealtype'), nullable=False),
    sa.Column('pre_bg', sa.Integer(), nullable=False),
    sa.Column('pre_bg_time', sa.DateTime(), nullable=False),
    sa.Column('post_bg', sa.Integer(), nullable=True),
    sa.Column('post_bg_time', sa.DateTime(), nullable=True),
    sa.Column('elapsed_min', sa.Integer(), nullable=True),
    sa.Column('meal_bolus_units', sa.Float(), nullable=False),
    sa.Column('correction_bolus_units', sa.Float(), nullable=False),
    sa.Column('bolus_offset_min', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('net_carbs_g', sa.Float(), sa.Computed('max(carbs_g - fiber_g, 0)', persisted=True), nullable=False),
    sa.Column('macro_confidence', sa.Integer(), nullable=False),
    sa.Column('ex_intensity', sa.Enum('none', 'light', 'intense', name='exintensity'), nullable=False),
    sa.Column('ex_duration_min', sa.Integer(), nullable=False),
    sa.Column('ex_offset_min', sa.Integer(), nullable=True),
    sa.Column('pre_ex_intensity', sa.Enum('none', 'light', 'intense', name='exintensity'), nullable=False),
    sa.Column('pre_ex_duration_min', sa.Integer(), nullable=False),
    sa.Column('hypo_treatment', sa.Boolean(), nullable=False),
    sa.Column('hypo_treatment_g', sa.Float(), nullable=True),
    sa.Column('snack_during_window', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reasons', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_table('model_artifact',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('fit_date', sa.DateTime(), nullable=False),
    sa.Column('data_hash', sa.String(), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('feature_list', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('is_promoted', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_tripped', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('patient_profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('icr', sa.Float(), nullable=True),
    sa.Column('isf', sa.Float(), nullable=False),
    sa.Column('isf_source', sa.Enum('default', 'endo', 'derived', name='isfsource'), nullable=False),
    sa.Column('target_bg', sa.Integer(), nullable=False),
    sa.Column('bolus_brand', sa.String(), nullable=False),
    sa.Column('basal_brand', sa.String(), nullable=False),
    sa.Column('hypo_unaware', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('bolus_log',
    sa.Column('bolus_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('bolus_type', sa.Enum('meal', 'correction', 'combined', name='bolustype'), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('logged_by', sa.Enum('patient', 'operator', name='loggedby'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_event.meal_id'], ),
    sa.PrimaryKeyConstraint('bolus_id')
    )
    op.create_table('prediction_log',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('gate_state', sa.String(), nullable=False),
    sa.Column('input_features', sa.JSON(), nullable=False),
    sa.Column('predicted_distribution', sa.JSON(), nullable=False),
    sa.Column('baseline_state', sa.Integer(), nullable=False),
    sa.Column('guardrail_fired', sa.String(), nullable=True),
    sa.Column('actual_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_event.meal_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_log')
    op.drop_table('bolus_log')
    op.drop_table('patient_profile')
    op.drop_table('model_artifact')
    op.drop_table('meal_event')
    op.drop_table('dish')
    op.drop_table('correction_event')
    op.drop_table('basal_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
